apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-api
  labels:
    app: k8s-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      containers:
      - name: e-commerce-api
        image: 774429751797.dkr.ecr.us-west-2.amazonaws.com/k8s-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
