apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-api
subjects:
- kind: ServiceAccount
  name: k8s-api-dev
  namespace: dev
roleRef:
  kind: ClusterRole
  name: k8s-api
  apiGroup: rbac.authorization.k8s.io