name: Main

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  test:
    uses: lucasmlp/actions/.github/workflows/go.test.yml@master
    with:
      go-version: '1.18'
      timeout-minutes: 5

  build:
    needs: test
    uses: lucasmlp/actions/.github/workflows/docker.build.yml@master
    with:
      timeout-minutes: 10
      aws-region: ${{ vars.AWS_REGION }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}