name: Main

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  test:
    uses: lucasmlp/actions/.github/workflows/go.test.yml@master
    with:
      go-version: '1.18'

  build:
    uses: lucasmlp/actions/.github/workflows/go.build.yml@master