name: Release

on:
  push:
    tags:        
      - '*'

jobs:
  release-version:
    steps:
      - name: Set Release Version
        id: set-release-version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  build:
    needs: release-version
    uses: lucasmlp/actions/.github/workflows/docker.build.yml@v1.1.0-rc.0
    with:
      timeout-minutes: 5
      aws-region: ${{ vars.AWS_REGION }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      tag: ${{ env.RELEASE_VERSION }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}