name: Main

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    uses: lucasmlp/actions/.github/workflows/docker.build.yml@v1.1.0-rc.0
    with:
      timeout-minutes: 5
      aws-region: ${{ vars.AWS_REGION }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      tag: ${GITHUB_REF#refs/*/}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}